apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  admin-user: "admin"
  admin-password: "mysecurepassword"
  GRAFANA_CLIENT_SECRET: "myclientsecret"