apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: grafana
type: Opaque
stringData:
  # Admin credentials
  admin-user: "admin"
  admin-password: "changeme"

  # Keycloak OAuth
  GRAFANA_CLIENT_SECRET: "changeme"